package interfaz;

import static interfaz.DialogInformes.seleccionUnidadGuardarInforme;
import interfaz.tablas.TableModelCarrerasConParticipantes;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logica.LogicaNegocio;
import modelo.Carrera;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import org.openide.util.Exceptions;

/**
 *
 * @author Shaila
 */
public class DialogTablaCarrerasFinalizadasInformes extends javax.swing.JDialog {

    private static final String RUTA_LOGO = ".." + File.separator + "imgs"
            + File.separator + "corredor.png";
    private int posicionCarreraFinalizada;
    /**
     * Creates new form TablaCorredores
     */
    LogicaNegocio logicaNegocio = LogicaNegocio.getInstance();

    public DialogTablaCarrerasFinalizadasInformes(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(null);
        setTitle("TABLA CARRERAS FINALIZADAS.");

        //Establecer el logo del a aplicación
        //setIconImage(new ImageIcon(getClass().getResource(RUTA_LOGO)).getImage());
        rellenarTablaCarrerasFinalizadas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpanelFondo1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCarreras = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JpanelFondo1.setBackground(new java.awt.Color(0, 153, 204));
        JpanelFondo1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carreras Finalizadas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 16))); // NOI18N
        JpanelFondo1.setMaximumSize(new java.awt.Dimension(950, 400));
        JpanelFondo1.setMinimumSize(new java.awt.Dimension(950, 400));

        jLabel2.setBackground(new java.awt.Color(255, 204, 255));
        jLabel2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 255));
        jLabel2.setText("Listado de Carreras:");
        jLabel2.setToolTipText("Introduzca euros a apostar");

        jTableCarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCarreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCarrerasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCarreras);

        javax.swing.GroupLayout JpanelFondo1Layout = new javax.swing.GroupLayout(JpanelFondo1);
        JpanelFondo1.setLayout(JpanelFondo1Layout);
        JpanelFondo1Layout.setHorizontalGroup(
            JpanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelFondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpanelFondo1Layout.setVerticalGroup(
            JpanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelFondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JpanelFondo1, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JpanelFondo1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableCarrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCarrerasMouseClicked
      
        int seleccionado = jTableCarreras.getSelectedRow();

        if (seleccionado == -1) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún registro.",
                    "¡¡ERROR!!", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                //Obtenemos la lista a mostrar
                List<Carrera> listaCarreras = new ArrayList<Carrera>();

                listaCarreras.add(logicaNegocio.getListaCarreras().get(seleccionado));

//La encapsulamos en el objeto adecuado
                JRDataSource dataSource = new JRBeanCollectionDataSource(listaCarreras);
//Creamos el map para los parámetros, en este caso va vacío.
                Map parametros = new HashMap();
                JasperPrint print = JasperFillManager.fillReport(
                        "informe3.jasper", parametros, dataSource);
                JasperExportManager.exportReportToPdfFile(print, seleccionUnidadGuardarInforme
                        + File.separator + "Informe3.pdf");

            } catch (JRException ex) {
                Exceptions.printStackTrace(ex);
            }
            this.dispose();
            JOptionPane.showMessageDialog(this, "Se ha generado el informe satisfactoriamente.",
                    "Informe 3.", JOptionPane.INFORMATION_MESSAGE);

        }


    }//GEN-LAST:event_jTableCarrerasMouseClicked

//Utilizando un AbstractTableModel
    private void rellenarTablaCarrerasFinalizadas() {
        jTableCarreras.setModel(new TableModelCarrerasConParticipantes(
                logicaNegocio.getListaCarrerasFinalizadas()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelFondo1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCarreras;
    // End of variables declaration//GEN-END:variables
}
