package interfaz;

import interfaz.tablas.TableModelCarreras;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import javax.swing.RowSorter.SortKey;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;
import logica.LogicaNegocio;
import modelo.Carrera;
import org.openide.util.Exceptions;

/**
 *
 * @author Shaila
 */
public class DialogTablaCarreras extends javax.swing.JDialog {

    private static final String RUTA_LOGO = ".." + File.separator + "imgs"
            + File.separator + "corredor.png";
    private int posicionCarreraFinalizada;
    /**
     * Creates new form TablaCorredores
     */
    LogicaNegocio logicaNegocio = LogicaNegocio.getInstance();

    public DialogTablaCarreras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ponLaAyuda();
        setLocationRelativeTo(null);
        setTitle("TABLA CARRERAS.");

        //Establecer el logo del a aplicación
        setIconImage(new ImageIcon(getClass().getResource(RUTA_LOGO)).getImage());
        rellenarTablaCarreras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTablaCarreras = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCarreras = new javax.swing.JTable();
        jButtonModificar = new javax.swing.JButton();
        jButtonAlta = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonResultadoCarreras = new javax.swing.JButton();
        jButtonGestionarCarrera = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuSalir1 = new javax.swing.JMenu();
        jMenuItemAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelTablaCarreras.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N

        jTableCarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCarreras);

        jButtonModificar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonModificar.setText("Modificar Carrera");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonAlta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonAlta.setText("Alta carrera");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jButtonBorrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonResultadoCarreras.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonResultadoCarreras.setText("Resultado Carreras");
        jButtonResultadoCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultadoCarrerasActionPerformed(evt);
            }
        });

        jButtonGestionarCarrera.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonGestionarCarrera.setText("Gestión Carrera");
        jButtonGestionarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionarCarreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTablaCarrerasLayout = new javax.swing.GroupLayout(jPanelTablaCarreras);
        jPanelTablaCarreras.setLayout(jPanelTablaCarrerasLayout);
        jPanelTablaCarrerasLayout.setHorizontalGroup(
            jPanelTablaCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaCarrerasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTablaCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelTablaCarrerasLayout.createSequentialGroup()
                        .addComponent(jButtonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonModificar))
                    .addComponent(jButtonGestionarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelTablaCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonResultadoCarreras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jButtonBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTablaCarrerasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTablaCarrerasLayout.setVerticalGroup(
            jPanelTablaCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaCarrerasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanelTablaCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelTablaCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTablaCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonResultadoCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGestionarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jMenuBar2.setBackground(new java.awt.Color(102, 153, 255));

        jMenuSalir1.setText(org.openide.util.NbBundle.getMessage(DialogTablaCarreras.class, "DialogGestionarCarrera.jMenuSalir1.text")); // NOI18N
        jMenuSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalir1ActionPerformed(evt);
            }
        });

        jMenuItemAyuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemAyuda.setText(org.openide.util.NbBundle.getMessage(DialogTablaCarreras.class, "DialogGestionarCarrera.jMenuItemAyuda.text")); // NOI18N
        jMenuItemAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAyudaActionPerformed(evt);
            }
        });
        jMenuSalir1.add(jMenuItemAyuda);

        jMenuBar2.add(jMenuSalir1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelTablaCarreras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelTablaCarreras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        int seleccionado = jTableCarreras.getSelectedRow();
        if (seleccionado == -1) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún registro.",
                    "!!ERROR!!", JOptionPane.ERROR_MESSAGE);

        } else if (logicaNegocio.getListaCarreras().get(seleccionado).isFinalizada()) {
            JOptionPane.showMessageDialog(this, "Carrera ya finalizada, no se puede modificar.",
                    "¡¡ERROR!!", JOptionPane.ERROR_MESSAGE);

        } else {
            Carrera carreraModificar = logicaNegocio.getListaCarreras().get(seleccionado);
            DialogFormularioCarreras dialogoModificar = new DialogFormularioCarreras(this,
                    true, carreraModificar);
            dialogoModificar.setLocationRelativeTo(null);
            dialogoModificar.setVisible(true);
            rellenarTablaCarreras();
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        DialogFormularioCarreras dialogoAlta = new DialogFormularioCarreras(this, true, logicaNegocio);
        dialogoAlta.setLocationRelativeTo(null);
        dialogoAlta.setVisible(true);
        rellenarTablaCarreras();
    }//GEN-LAST:event_jButtonAltaActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed

        int seleccionado = jTableCarreras.getSelectedRow();
        if (seleccionado == -1) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún registro.",
                    "!!ERROR!!", JOptionPane.ERROR_MESSAGE);

        } else if (logicaNegocio.getListaCarreras().get(seleccionado).isFinalizada()) {
            JOptionPane.showMessageDialog(this, "Carrera ya finalizada, no se puede borrar.",
                    "¡¡ERROR!!", JOptionPane.ERROR_MESSAGE);
        } else {
            Carrera carreraBorrar = logicaNegocio.getListaCarreras()
                    .get(seleccionado);

            int confirmación = JOptionPane.showConfirmDialog(this, "¿Quiere borrar el registro?",
                    "Confirmación", JOptionPane.YES_NO_CANCEL_OPTION);
            if (confirmación == JOptionPane.YES_OPTION) {
                logicaNegocio.borrarCarrera(carreraBorrar);
                JOptionPane.showMessageDialog(this, "Se ha borrado la carrera.",
                        "Borrar.", JOptionPane.INFORMATION_MESSAGE);
            } else if (confirmación == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(this, "No se ha borrado la carrera.",
                        "Borrar.", JOptionPane.INFORMATION_MESSAGE);
            }
            rellenarTablaCarreras();
        }
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonGestionarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionarCarreraActionPerformed

        int seleccionado = jTableCarreras.convertRowIndexToModel(jTableCarreras.getSelectedRow());

        if (seleccionado == -1) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún registro.",
                    "¡¡ERROR!!", JOptionPane.ERROR_MESSAGE);
        } else {
            if (!logicaNegocio.getListaCarreras().get(seleccionado).isFinalizada()) {
                posicionCarreraFinalizada = logicaNegocio.getListaCarrerasFinalizadas().size();
                Carrera carreraAcorrer = logicaNegocio.getListaCarreras().get(seleccionado);
                logicaNegocio.setIdCarrera(posicionCarreraFinalizada);
                carreraAcorrer.setIdCarrera(posicionCarreraFinalizada);

                DialogGestionarCarrera dialogGestionarCarrera = new DialogGestionarCarrera(this, true,
                        carreraAcorrer);
                dialogGestionarCarrera.setLocationRelativeTo(null);
                dialogGestionarCarrera.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Carrera ya finalizada.",
                        "¡¡ERROR!!", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButtonGestionarCarreraActionPerformed

    private void jButtonResultadoCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultadoCarrerasActionPerformed

        DialogTablaCarrerasFinalizadas resultadoCarreraFinalizada
                = new DialogTablaCarrerasFinalizadas(this, true);
        resultadoCarreraFinalizada.setLocationRelativeTo(null);
        resultadoCarreraFinalizada.setVisible(true);


    }//GEN-LAST:event_jButtonResultadoCarrerasActionPerformed

    private void jMenuItemAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAyudaActionPerformed

    }//GEN-LAST:event_jMenuItemAyudaActionPerformed

    private void jMenuSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalir1ActionPerformed

    }//GEN-LAST:event_jMenuSalir1ActionPerformed

//Utilizando un AbstractTableModel
    private void rellenarTablaCarreras() {

        //La lista que tenemos en logica negocio no la tocamos, va a ser el jtable quién lo haga
        TableModelCarreras tableModelCarreras = new TableModelCarreras(logicaNegocio.getListaCarreras());
        jTableCarreras.setModel(tableModelCarreras);
        TableRowSorter<TableModelCarreras> sorter = new TableRowSorter<>(tableModelCarreras);
        jTableCarreras.setRowSorter(sorter);

        List<SortKey> sortKeys = new ArrayList<>();
        //Creamos uno nuevo y le pasamos dos valores, 
        //el primero la columna por la que queremos ordenar y el orden
        sortKeys.add(new SortKey(1,SortOrder.ASCENDING));
        //indicar claves ordenación
        sorter.setSortKeys(sortKeys);
        
    }

        /**
     * Método que incorpora la ayuda en nuestro proyecto.
     */
    private void ponLaAyuda() {
        try {
            //Carga el fichero de ayuda
            File fichero = new File("help" + File.separator + "help_set.hs");
            URL hsURL = fichero.toURI().toURL();

            //Si metemos la carpeta help en src tenemos que quitar lo anterior y poner
            /**
             * URL ayuda = getClass().getResource("ruta"); File
             * ficheroAyudaEnJar = new File(ayuda.toURI());
             */
            //Crea el HelpSet y el HelpBroker
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            /**
             * Pone ayuda a item de menu al pulsarlo y a F1 en ventana ppal y
             * secundaria.
             */
            hb.enableHelpOnButton(jMenuItemAyuda, "aplicacion", helpset);
            //Al pulsar F1 salta la ayuda
            hb.enableHelpKey(getRootPane(), "aplicacion", helpset);
            /*hb.enableHelpKey(jButton1, "ventana_principal", helpset);
            hb.enableHelpKey(jButton2, "ventana_secundaria", helpset);
            hb.enableHelpKey(jButton1, "ventana_principal", helpset);
            hb.enableHelpKey(jButton2, "ventana_secundaria", helpset);*/
        } catch (MalformedURLException ex) {
            Exceptions.printStackTrace(ex);
        } catch (HelpSetException ex) {
            Exceptions.printStackTrace(ex);
        }

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonGestionarCarrera;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonResultadoCarreras;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItemAyuda;
    private javax.swing.JMenu jMenuSalir1;
    private javax.swing.JPanel jPanelTablaCarreras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCarreras;
    // End of variables declaration//GEN-END:variables
}
