package interfaz;


import interfaz.tablas.TableModelCarrerasConParticipantes;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logica.LogicaNegocio;


/**
 *
 * @author Shaila
 */
public class DialogTablaCarrerasFinalizadas extends javax.swing.JDialog {

    private static final String RUTA_LOGO = ".." + File.separator + "imgs"
            + File.separator + "corredor.png";
    private int posicionCarreraFinalizada;
    /**
     * Creates new form TablaCorredores
     */
    LogicaNegocio logicaNegocio = LogicaNegocio.getInstance();

    public DialogTablaCarrerasFinalizadas(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(null);
        setTitle("TABLA CARRERAS FINALIZADAS.");

        //Establecer el logo del a aplicación
        //setIconImage(new ImageIcon(getClass().getResource(RUTA_LOGO)).getImage());
        rellenarTablaCarrerasFinalizadas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpanelFondo1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCarreras = new javax.swing.JTable();
        jButtonResultadoCarreras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JpanelFondo1.setBackground(new java.awt.Color(0, 153, 204));
        JpanelFondo1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carreras Finalizadas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 16))); // NOI18N
        JpanelFondo1.setMaximumSize(new java.awt.Dimension(950, 400));
        JpanelFondo1.setMinimumSize(new java.awt.Dimension(950, 400));

        jLabel2.setBackground(new java.awt.Color(255, 204, 255));
        jLabel2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 255));
        jLabel2.setText("Listado de Carreras:");
        jLabel2.setToolTipText("Introduzca euros a apostar");

        jTableCarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableCarreras);

        jButtonResultadoCarreras.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonResultadoCarreras.setText("Resultado Carreras");
        jButtonResultadoCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultadoCarrerasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpanelFondo1Layout = new javax.swing.GroupLayout(JpanelFondo1);
        JpanelFondo1.setLayout(JpanelFondo1Layout);
        JpanelFondo1Layout.setHorizontalGroup(
            JpanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelFondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonResultadoCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JpanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpanelFondo1Layout.setVerticalGroup(
            JpanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelFondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonResultadoCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JpanelFondo1, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JpanelFondo1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResultadoCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultadoCarrerasActionPerformed
        int seleccionado = jTableCarreras.getSelectedRow();

        if (seleccionado == -1) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún registro.",
                "¡¡ERROR!!", JOptionPane.ERROR_MESSAGE);
        } else {

            DialogResultadoCarreraFinalizada resultadoCarreraFinalizada
            = new DialogResultadoCarreraFinalizada(this, true, logicaNegocio.
                getListaCarreras().get(seleccionado).getIdCarrera());
            resultadoCarreraFinalizada.setLocationRelativeTo(null);
            resultadoCarreraFinalizada.setVisible(true);

        }
    }//GEN-LAST:event_jButtonResultadoCarrerasActionPerformed

//Utilizando un AbstractTableModel
    private void rellenarTablaCarrerasFinalizadas() {
        jTableCarreras.setModel(new TableModelCarrerasConParticipantes(
                logicaNegocio.getListaCarrerasFinalizadas()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelFondo1;
    private javax.swing.JButton jButtonResultadoCarreras;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCarreras;
    // End of variables declaration//GEN-END:variables
}
