package interfaz;

import java.io.File;
import java.sql.Connection;
import java.util.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import logica.LogicaNegocio;
import modelo.Carrera;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import org.openide.util.Exceptions;

/**
 *
 * @author Shaila
 */
public class DialogInformes extends javax.swing.JDialog {

    static String seleccionUnidadGuardarInforme;
    private Connection connection;
    private File carpetaInformes;

    /**
     * Creates new form DialogConfiguracion
     */
    public DialogInformes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("INFORMES.");
        jButtonGenerarInforme1.setEnabled(false);
        jButtonGenerarInforme2.setEnabled(false);
        jButtonGenerarInforme3.setEnabled(false);
        jButtonGenerarInforme4.setEnabled(false);
        jLabelOpcion.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelSelecionarRuta = new javax.swing.JLabel();
        jButtonSeleccionarRuta = new javax.swing.JButton();
        jButtonGenerarInforme1 = new javax.swing.JButton();
        jButtonGenerarInforme2 = new javax.swing.JButton();
        jButtonGenerarInforme3 = new javax.swing.JButton();
        jButtonGenerarInforme4 = new javax.swing.JButton();
        jLabelOpcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(DialogInformes.class, "DialogInformes.jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 16))); // NOI18N

        jButtonSalir.setBackground(new java.awt.Color(204, 204, 255));
        jButtonSalir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonSalir.setText(org.openide.util.NbBundle.getMessage(DialogInformes.class, "DialogInformes.jButtonSalir.text_1")); // NOI18N
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(DialogInformes.class, "DialogInformes.jPanel4.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        jLabelSelecionarRuta.setBackground(new java.awt.Color(255, 204, 255));
        jLabelSelecionarRuta.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelSelecionarRuta.setForeground(new java.awt.Color(255, 204, 255));
        jLabelSelecionarRuta.setText(org.openide.util.NbBundle.getMessage(DialogInformes.class, "DialogInformes.jLabelSelecionarRuta.text")); // NOI18N
        jLabelSelecionarRuta.setToolTipText(org.openide.util.NbBundle.getMessage(DialogInformes.class, "DialogInformes.jLabelSelecionarRuta.toolTipText")); // NOI18N

        jButtonSeleccionarRuta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonSeleccionarRuta.setText(org.openide.util.NbBundle.getMessage(DialogInformes.class, "DialogInformes.jButtonSeleccionarRuta.text")); // NOI18N
        jButtonSeleccionarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarRutaActionPerformed(evt);
            }
        });

        jButtonGenerarInforme1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonGenerarInforme1.setText(org.openide.util.NbBundle.getMessage(DialogInformes.class, "DialogInformes.jButtonGenerarInforme1.text_1")); // NOI18N
        jButtonGenerarInforme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarInforme1ActionPerformed(evt);
            }
        });

        jButtonGenerarInforme2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonGenerarInforme2.setText(org.openide.util.NbBundle.getMessage(DialogInformes.class, "DialogInformes.jButtonGenerarInforme2.text")); // NOI18N
        jButtonGenerarInforme2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarInforme2ActionPerformed(evt);
            }
        });

        jButtonGenerarInforme3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonGenerarInforme3.setText(org.openide.util.NbBundle.getMessage(DialogInformes.class, "DialogInformes.jButtonGenerarInforme3.text")); // NOI18N
        jButtonGenerarInforme3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarInforme3ActionPerformed(evt);
            }
        });

        jButtonGenerarInforme4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonGenerarInforme4.setText(org.openide.util.NbBundle.getMessage(DialogInformes.class, "DialogInformes.jButtonGenerarInforme4.text")); // NOI18N
        jButtonGenerarInforme4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarInforme4ActionPerformed(evt);
            }
        });

        jLabelOpcion.setBackground(new java.awt.Color(255, 204, 255));
        jLabelOpcion.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabelOpcion.setForeground(new java.awt.Color(255, 204, 255));
        jLabelOpcion.setText(org.openide.util.NbBundle.getMessage(DialogInformes.class, "DialogInformes.jLabelOpcion.text")); // NOI18N
        jLabelOpcion.setToolTipText(org.openide.util.NbBundle.getMessage(DialogInformes.class, "DialogInformes.jLabelOpcion.toolTipText")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSelecionarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonGenerarInforme1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSeleccionarRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGenerarInforme2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGenerarInforme3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGenerarInforme4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSelecionarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSeleccionarRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addComponent(jButtonGenerarInforme1)
                        .addGap(0, 0, 0))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(jButtonGenerarInforme2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addComponent(jButtonGenerarInforme3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addComponent(jButtonGenerarInforme4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerarInforme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarInforme1ActionPerformed

        try {
            //Obtenemos la lista a mostrar
            List<Carrera> listaCarreras = new ArrayList<Carrera>();
            List<Carrera> listaCarrerasSinFinalizar = LogicaNegocio.getInstance().getListaCarreras();

            for (Iterator<Carrera> iterator = listaCarrerasSinFinalizar.iterator(); iterator.hasNext();) {
                Carrera carreraSinFinalizar = iterator.next();

                if (carreraSinFinalizar.getEstado().equalsIgnoreCase("Pendiente")) {
                    listaCarreras.add(carreraSinFinalizar);
                }

            }

//La encapsulamos en el objeto adecuado
            JRDataSource dataSource = new JRBeanCollectionDataSource(listaCarreras);

//Creamos el map para los parámetros, en este caso va vacío.
            Map parametros = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(
                    "informe1.jasper", parametros, dataSource);

            JasperExportManager.exportReportToPdfFile(print, carpetaInformes.
                    getAbsolutePath() + File.separator + "Informe1.pdf");

        } catch (JRException ex) {
            Exceptions.printStackTrace(ex);
        }
        //this.dispose();
        JOptionPane.showMessageDialog(this, "Se ha generado el informe satisfactoriamente.",
                "Informe 1.", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonGenerarInforme1ActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed

        this.dispose();

    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonSeleccionarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarRutaActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setMultiSelectionEnabled(false);
        int returnSelection = chooser.showOpenDialog(null);
        if (returnSelection == JFileChooser.APPROVE_OPTION) {
            seleccionUnidadGuardarInforme = chooser.getSelectedFile().getAbsolutePath();
            carpetaInformes = new File(seleccionUnidadGuardarInforme + File.separator + "informes_Ireport");
            if (!carpetaInformes.exists()) {
                carpetaInformes.mkdir();
                seleccionUnidadGuardarInforme = carpetaInformes.getAbsolutePath();
            } else {
//Poner que seleccione la carpeta
                seleccionUnidadGuardarInforme = carpetaInformes.getAbsolutePath();
            }
        }
        jButtonGenerarInforme1.setEnabled(true);
        jButtonGenerarInforme2.setEnabled(true);
        jButtonGenerarInforme3.setEnabled(true);
        jButtonGenerarInforme4.setEnabled(true);
        jLabelOpcion.setVisible(true);

        jButtonSeleccionarRuta.setEnabled(false);
        jLabelSelecionarRuta.setEnabled(false);

    }//GEN-LAST:event_jButtonSeleccionarRutaActionPerformed

    private void jButtonGenerarInforme2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarInforme2ActionPerformed

        DialogTablaCarrerasInformes dialogTablaCarreras = new DialogTablaCarrerasInformes(this, true);
        dialogTablaCarreras.setLocationRelativeTo(null);
        dialogTablaCarreras.setVisible(true);


    }//GEN-LAST:event_jButtonGenerarInforme2ActionPerformed

    private void jButtonGenerarInforme3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarInforme3ActionPerformed

        DialogTablaCarrerasFinalizadasInformes dialogCarrerasFinalizadas = new DialogTablaCarrerasFinalizadasInformes(this, true);
        dialogCarrerasFinalizadas.setLocationRelativeTo(null);
        dialogCarrerasFinalizadas.setVisible(true);


    }//GEN-LAST:event_jButtonGenerarInforme3ActionPerformed

    private void jButtonGenerarInforme4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarInforme4ActionPerformed

        DialogTablaCorredoresInformes dialogCorredoresInformes
                = new DialogTablaCorredoresInformes(this, true);
        dialogCorredoresInformes.setLocationRelativeTo(null);
        dialogCorredoresInformes.setVisible(true);


    }//GEN-LAST:event_jButtonGenerarInforme4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerarInforme1;
    private javax.swing.JButton jButtonGenerarInforme2;
    private javax.swing.JButton jButtonGenerarInforme3;
    private javax.swing.JButton jButtonGenerarInforme4;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSeleccionarRuta;
    private javax.swing.JLabel jLabelOpcion;
    private javax.swing.JLabel jLabelSelecionarRuta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
