/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import interfaz.tablas.TableModelParticipantes;
import logica.LogicaNegocio;

/**
 *
 * @author Mario
 */
public class DialogResultadoCarreraFinalizada extends javax.swing.JDialog {

    private int idCarrera;

    /**
     * Creates new form ResultadoCarrera
     */
    public DialogResultadoCarreraFinalizada(java.awt.Dialog parent, boolean modal,
            int idCarrera) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.idCarrera = idCarrera;
        setTitle("LISTA PARTICIPANTES DE "+LogicaNegocio.getInstance().
                getListaCarrerasFinalizadas().get(idCarrera).getNombreCarrera()+".");
        jLabelNombreCarrera.setText(LogicaNegocio.getInstance().getListaCarrerasFinalizadas().get(idCarrera).getNombreCarrera());
        jLabelTiempoCarrera.setText(LogicaNegocio.getInstance().getListaCarrerasFinalizadas().get(idCarrera).getTiempoTotal());

        rellenarTablaParticipantes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabelNombreCarrera = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResultadoCarrera = new javax.swing.JTable();
        jLabelTiempoCarrera = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNombreCarrera.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelNombreCarrera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreCarrera.setText("Carrera");

        jTableResultadoCarrera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(jTableResultadoCarrera);

        jLabelTiempoCarrera.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTiempoCarrera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTiempoCarrera.setText("Tiempo");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLabelTiempoCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLabelNombreCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNombreCarrera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTiempoCarrera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rellenarTablaParticipantes() {

        jTableResultadoCarrera.setModel(new TableModelParticipantes(
                LogicaNegocio.getInstance().getListaCarrerasFinalizadas().get(idCarrera).getListaParticipantes()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelNombreCarrera;
    private javax.swing.JLabel jLabelTiempoCarrera;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResultadoCarrera;
    // End of variables declaration//GEN-END:variables
}
