package interfaz;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import interfaz.DialogTablaCarreras;
import interfaz.DialogTablaCorredores;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logica.GestionGuardado;
import logica.LogicaNegocio;
import org.openide.util.Exceptions;

/**
 * Los combos se rellenan siempre en constructor porque no funciona, hacer una
 * función para rellenar, privada
 *
 * @author Shaila
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /*    private static final String RUTA_LOGO = ".." + File.separator + "imgs"
    + File.separator + "corredor.png";*/
    private static final String RUTA_IMAGEN = ".." + File.separator + "imgs"
            + File.separator + "Runners.png";
    
    private boolean paginaPrincipal = false;

    /**
     * Creates new form PantallaPrincipal
     */
    LogicaNegocio logicaNegocio = LogicaNegocio.getInstance();

    public PantallaPrincipal() throws ParseException {
        initComponents();
        //ponLaAyuda();
        //this.setExtendedState(this.MAXIMIZED_BOTH); //MAXIMIZAR FORMULARIO
        setLocationRelativeTo(null);
        //Establecer el título de la aplicación
        setTitle("APLICACIÓN GESTIÓN CARRERAS.");

        File archivo = new File("LogicaNegocio.dat");
        if (!archivo.exists()) {
            logicaNegocio.cargarCSVCorredores();
        }
        //Establecer una imagen en una label
        //jLabelIcono.setIcon(new ImageIcon(getClass().getResource(RUTA_IMAGEN)));
        jButtonModificarCorredores.setText("<html><p>BBDD </p>"
                + "<p>CORREDORES</p></html>");
        jButtonModificarCarrera.setText("<html><p>ALTA/MODIFICACIÓN</p>"
                + "<p>CARRERAS</p></html>");
        //Establecer el logo del a aplicación
        //setIconImage(new ImageIcon(getClass().getResource(RUTA_LOGO)).getImage());

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                super.windowClosing(we);
                //Meter aquí la logica grabar datos
                //if (LogicaNegocio.getInstance().getListaCarrerasIniciar().size() != 0) {
                //LogicaNegocio.getInstance().grabarCarrera();
                GestionGuardado.salvarCambios();
                //}

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanelPantallaPrincipal = new javax.swing.JPanel();
        JpanelFondo = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelIcono = new javax.swing.JLabel();
        jButtonModificarCarrera = new javax.swing.JButton();
        jButtonModificarCorredores = new javax.swing.JButton();
        jButtonSaliAplicacion = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuConfiguracion = new javax.swing.JMenu();
        jMenuItemConfiguracion = new javax.swing.JMenuItem();
        jCheckBoxMenuItemGrabadoAutomatico = new javax.swing.JCheckBoxMenuItem();
        jMenuGenerarInformes = new javax.swing.JMenu();
        jMenuItemGenerarInformes = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemSalirAplicacion = new javax.swing.JMenuItem();
        jMenuItemAyuda = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPantallaPrincipal.setToolTipText("");

        JpanelFondo.setBackground(new java.awt.Color(0, 153, 204));
        JpanelFondo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestión de Carreras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 16))); // NOI18N
        JpanelFondo.setMaximumSize(new java.awt.Dimension(950, 400));
        JpanelFondo.setMinimumSize(new java.awt.Dimension(950, 400));

        panel2.setBackground(new java.awt.Color(102, 153, 255));
        panel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alta y Modificación en Base de Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        panel2.setMaximumSize(new java.awt.Dimension(700, 200));
        panel2.setMinimumSize(new java.awt.Dimension(700, 200));

        jLabel2.setBackground(new java.awt.Color(255, 204, 255));
        jLabel2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 255));
        jLabel2.setText("Seleccione una opción");
        jLabel2.setToolTipText("Introduzca euros a apostar");

        jLabelIcono.setPreferredSize(new java.awt.Dimension(60, 100));

        jButtonModificarCarrera.setBackground(new java.awt.Color(204, 204, 255));
        jButtonModificarCarrera.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonModificarCarrera.setText("ALTA/MODIFICACIÓN CARRERAS");
        jButtonModificarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarCarreraActionPerformed(evt);
            }
        });

        jButtonModificarCorredores.setBackground(new java.awt.Color(204, 204, 255));
        jButtonModificarCorredores.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonModificarCorredores.setText("BBDD CORREDORES");
        jButtonModificarCorredores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarCorredoresActionPerformed(evt);
            }
        });

        jButtonSaliAplicacion.setBackground(new java.awt.Color(204, 204, 255));
        jButtonSaliAplicacion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonSaliAplicacion.setText("SALIR");
        jButtonSaliAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaliAplicacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSaliAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonModificarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonModificarCorredores, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonModificarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonModificarCorredores, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSaliAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout JpanelFondoLayout = new javax.swing.GroupLayout(JpanelFondo);
        JpanelFondo.setLayout(JpanelFondoLayout);
        JpanelFondoLayout.setHorizontalGroup(
            JpanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelFondoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        JpanelFondoLayout.setVerticalGroup(
            JpanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanelPantallaPrincipalLayout = new javax.swing.GroupLayout(jPanelPantallaPrincipal);
        jPanelPantallaPrincipal.setLayout(jPanelPantallaPrincipalLayout);
        jPanelPantallaPrincipalLayout.setHorizontalGroup(
            jPanelPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPantallaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JpanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanelPantallaPrincipalLayout.setVerticalGroup(
            jPanelPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPantallaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JpanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 153, 255));

        jMenuConfiguracion.setText("Configuracion");

        jMenuItemConfiguracion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemConfiguracion.setText("Configuracion");
        jMenuItemConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConfiguracionActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuItemConfiguracion);

        jCheckBoxMenuItemGrabadoAutomatico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItemGrabadoAutomatico.setText("Grabado automático");
        jCheckBoxMenuItemGrabadoAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemGrabadoAutomaticoActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jCheckBoxMenuItemGrabadoAutomatico);

        jMenuBar1.add(jMenuConfiguracion);

        jMenuGenerarInformes.setText("Informes");
        jMenuGenerarInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGenerarInformesActionPerformed(evt);
            }
        });

        jMenuItemGenerarInformes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemGenerarInformes.setText("Generar Informes");
        jMenuItemGenerarInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGenerarInformesActionPerformed(evt);
            }
        });
        jMenuGenerarInformes.add(jMenuItemGenerarInformes);

        jMenuBar1.add(jMenuGenerarInformes);

        jMenuSalir.setText("Ayuda");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });

        jMenuItemSalirAplicacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemSalirAplicacion.setText("Salir Aplicacion");
        jMenuItemSalirAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirAplicacionActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuItemSalirAplicacion);

        jMenuItemAyuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemAyuda.setText("Ayuda");
        jMenuItemAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAyudaActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuItemAyuda);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPantallaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPantallaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConfiguracionActionPerformed

        DialogConfiguracion dialogoConfiguracion = new DialogConfiguracion(this, true);
        dialogoConfiguracion.setLocationRelativeTo(null);
        dialogoConfiguracion.setVisible(true);
    }//GEN-LAST:event_jMenuItemConfiguracionActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed

    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuItemSalirAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirAplicacionActionPerformed
        //setVisible(false);  
        this.dispose();
        System.exit(0);//Este usarlo para salir porque el dispose me deja una pantalla.
    }//GEN-LAST:event_jMenuItemSalirAplicacionActionPerformed

    private void jCheckBoxMenuItemGrabadoAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemGrabadoAutomaticoActionPerformed

        if (jCheckBoxMenuItemGrabadoAutomatico.getState()) {
            String automaticSave = JOptionPane.showInputDialog("Introduzca tiempo "
                    + "autoguardado (minutos): ");
            try {
                LogicaNegocio.getInstance().iniciarGuardadoAutomatico(Integer.
                        parseInt(automaticSave));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "No ha introducido un número.",
                        "¡¡ERROR!!", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            String automaticSave = "0";
            LogicaNegocio.getInstance().iniciarGuardadoAutomatico(Integer.parseInt(automaticSave));
        }
    }//GEN-LAST:event_jCheckBoxMenuItemGrabadoAutomaticoActionPerformed
    /**
     * Crea un dialogo de mensaje con la ayuda de la aplicación.
     *
     * @param evt
     */
    private void jMenuItemAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAyudaActionPerformed


    }//GEN-LAST:event_jMenuItemAyudaActionPerformed

    private void jMenuItemGenerarInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGenerarInformesActionPerformed

        DialogInformes dialogoInformes = new DialogInformes(this, true);
        dialogoInformes.setLocationRelativeTo(null);
        dialogoInformes.setVisible(true);
    }//GEN-LAST:event_jMenuItemGenerarInformesActionPerformed

    private void jMenuGenerarInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGenerarInformesActionPerformed

    }//GEN-LAST:event_jMenuGenerarInformesActionPerformed

    private void jButtonModificarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarCarreraActionPerformed
        DialogTablaCarreras confirmacionValidar
                = new DialogTablaCarreras(this, true);
        confirmacionValidar.setVisible(true);
    }//GEN-LAST:event_jButtonModificarCarreraActionPerformed

    private void jButtonModificarCorredoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarCorredoresActionPerformed
        DialogTablaCorredores confirmacionValidar
                = new DialogTablaCorredores(this, true);
        confirmacionValidar.setVisible(true);
        paginaPrincipal = true;
    }//GEN-LAST:event_jButtonModificarCorredoresActionPerformed

    private void jButtonSaliAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaliAplicacionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSaliAplicacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PantallaPrincipal().setVisible(true);

                } catch (ParseException ex) {
                    Logger.getLogger(PantallaPrincipal.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    /**
     * Método que incorpora la ayuda en nuestro proyecto.
     */
    private void ponLaAyuda() {
        try {
            //Carga el fichero de ayuda
            File fichero = new File("help" + File.separator + "help_set.hs");
            URL hsURL = fichero.toURI().toURL();

            //Si metemos la carpeta help en src tenemos que quitar lo anterior y poner
            /**
             * URL ayuda = getClass().getResource("ruta"); File
             * ficheroAyudaEnJar = new File(ayuda.toURI());
             */
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            /**
             * Pone ayuda a item de menu al pulsarlo y a F1 en ventana ppal y
             * secundaria.
             */
            hb.enableHelpOnButton(jMenuItemAyuda, "aplicacion", helpset);
            //Al pulsar F1 salta la ayuda
            hb.enableHelpKey(getRootPane(), "aplicacion", helpset);
        } catch (MalformedURLException ex) {
            Exceptions.printStackTrace(ex);
        } catch (HelpSetException ex) {
            Exceptions.printStackTrace(ex);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelFondo;
    private javax.swing.JButton jButtonModificarCarrera;
    private javax.swing.JButton jButtonModificarCorredores;
    private javax.swing.JButton jButtonSaliAplicacion;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemGrabadoAutomatico;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConfiguracion;
    private javax.swing.JMenu jMenuGenerarInformes;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAyuda;
    private javax.swing.JMenuItem jMenuItemConfiguracion;
    private javax.swing.JMenuItem jMenuItemGenerarInformes;
    private javax.swing.JMenuItem jMenuItemSalirAplicacion;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JPanel jPanelPantallaPrincipal;
    private javax.swing.JPanel panel2;
    // End of variables declaration//GEN-END:variables

}
