/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Shaila
 */
public class DialogConfiguracion extends javax.swing.JDialog {

    /**
     * Creates new form DialogConfiguracion
     */
    public DialogConfiguracion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         setTitle("CONFIGURACIÓN.");
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();
        for (UIManager.LookAndFeelInfo lfi : UIManager.getInstalledLookAndFeels()) {
            dcm.addElement(lfi.getName());
        }
        jComboBoxLAndF.setModel(dcm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxLAndF = new javax.swing.JComboBox<>();
        jButtonAceptarTema = new javax.swing.JButton();
        jButtonSalirDelTodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBoxLAndF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLAndFActionPerformed(evt);
            }
        });

        jButtonAceptarTema.setText(org.openide.util.NbBundle.getMessage(DialogConfiguracion.class, "DialogConfiguracion.jButtonAceptarTema.text")); // NOI18N
        jButtonAceptarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarTemaActionPerformed(evt);
            }
        });

        jButtonSalirDelTodo.setBackground(new java.awt.Color(204, 204, 255));
        jButtonSalirDelTodo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonSalirDelTodo.setText(org.openide.util.NbBundle.getMessage(DialogConfiguracion.class, "DialogConfiguracion.jButtonSalirDelTodo.text")); // NOI18N
        jButtonSalirDelTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirDelTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAceptarTema)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalirDelTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBoxLAndF, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jComboBoxLAndF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAceptarTema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalirDelTodo, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxLAndFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLAndFActionPerformed
        try {
            UIManager.setLookAndFeel(UIManager.getInstalledLookAndFeels()[jComboBoxLAndF.getSelectedIndex()].getClassName());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Throwable e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBoxLAndFActionPerformed

    private void jButtonAceptarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarTemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAceptarTemaActionPerformed

    private void jButtonSalirDelTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirDelTodoActionPerformed

        this.dispose();

    }//GEN-LAST:event_jButtonSalirDelTodoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptarTema;
    private javax.swing.JButton jButtonSalirDelTodo;
    private javax.swing.JComboBox<String> jComboBoxLAndF;
    // End of variables declaration//GEN-END:variables
}
