package interfaz;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import logica.LogicaNegocio;
import modelo.Carrera;
import org.netbeans.validation.api.builtin.stringvalidation.MayusculaValidator;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 *
 * @author Shaila
 */
/*
Copiar javax.swing.JDialog y reemplazar java.awt.Frame
 */
public class FormularioCarreras extends javax.swing.JDialog {

    private SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yy");
    private static final String RUTA_LOGO = "..\\imgs\\corredor.png";
    private Carrera carreraModificar;
    private LogicaNegocio logicaNegocio;
    private String nombreCarrera = "";
    private Date fechaCarrera;
    private String lugarCarrera = "";
    private int numeroMaxCorredores;

    /**
     * Creates new form FormularioCarreras
     */
    
    //Constructor para el alta
    public FormularioCarreras(TablaCarreras aThis, boolean modal, LogicaNegocio logicaNegocio) {
        super(aThis, modal);
        this.logicaNegocio = LogicaNegocio.getInstance();
        initComponents();
        setTitle("FORMULARIO ALTA CARRERAS.");
        //Establecer el logo del a aplicación
        setIconImage(new ImageIcon(getClass().getResource(RUTA_LOGO)).getImage());
        setLocationRelativeTo(null);
        jButtonValidarCarrera.setEnabled(false);
        ValidationGroup group = validationPanel.getValidationGroup();
        group.add(jTextFieldNombreCarrera, StringValidators.REQUIRE_NON_EMPTY_STRING,
                new MayusculaValidator());

        validationPanel.addChangeListener((new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent ce) {
                if (validationPanel.getProblem() == null) {
                    jButtonValidarCarrera.setEnabled(true);
                } else {
                    jButtonValidarCarrera.setEnabled(false);
                }
            }
        }));
    }

    //Constructor para modificar. Sabemos diferenciar si es un alta o una modificación
    //gracias al valor de personaModificar. Si es null será un alta, si tiene un valor
    //será una modificación.
    public FormularioCarreras(TablaCarreras aThis, boolean modal, Carrera carreraModificar) {
        super(aThis, modal);
        this.carreraModificar = carreraModificar;
        initComponents();
        setTitle("FORMULARIO MODIFICACIÓN CARRERAS.");

//Establecer el logo del a aplicación
        setIconImage(new ImageIcon(getClass().getResource(RUTA_LOGO)).getImage());
        jButtonValidarCarrera.setEnabled(false);
        ValidationGroup group = validationPanel.getValidationGroup();
        group.add(jTextFieldNombreCarrera, StringValidators.REQUIRE_NON_EMPTY_STRING);

        validationPanel.addChangeListener((new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent ce) {
                if (validationPanel.getProblem() == null) {
                    jButtonValidarCarrera.setEnabled(true);
                } else {
                    jButtonValidarCarrera.setEnabled(false);
                }
            }
        }));
        jTextFieldNombreCarrera.setText(carreraModificar.getNombreCarrera());
        jComboBoxCiudad.setActionCommand(carreraModificar.getLugarCarrera());
        jComboBoxNumeroMaximoParticipantes.setSelectedIndex(
                carreraModificar.getNumeroMaxCorredores()+1);
        jSpinnerFechaCarrera.setValue(carreraModificar.getFechaCarrera());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTituloCarrera = new javax.swing.JPanel();
        jPanelDatosCarrera = new javax.swing.JPanel();
        jLabelNombreCarrera = new javax.swing.JLabel();
        jLabelFechaCarrera = new javax.swing.JLabel();
        jLabelLugarCarrera = new javax.swing.JLabel();
        jLabelNumeroMaxParticipantes = new javax.swing.JLabel();
        jTextFieldNombreCarrera = new javax.swing.JTextField();
        jSpinnerFechaCarrera = new javax.swing.JSpinner();
        jComboBoxCiudad = new javax.swing.JComboBox<>();
        jComboBoxNumeroMaximoParticipantes = new javax.swing.JComboBox<>();
        jPanelBotonesCarrera = new javax.swing.JPanel();
        jButtonSalirCarrera = new javax.swing.JButton();
        jButtonValidarCarrera = new javax.swing.JButton();
        jButtonLimpiarCarrera = new javax.swing.JButton();
        validationPanel = new org.netbeans.validation.api.ui.swing.ValidationPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanelTituloCarreraLayout = new javax.swing.GroupLayout(jPanelTituloCarrera);
        jPanelTituloCarrera.setLayout(jPanelTituloCarreraLayout);
        jPanelTituloCarreraLayout.setHorizontalGroup(
            jPanelTituloCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelTituloCarreraLayout.setVerticalGroup(
            jPanelTituloCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        jLabelNombreCarrera.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNombreCarrera.setText("Nombre Carrera");

        jLabelFechaCarrera.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelFechaCarrera.setText("Fecha de la carrera");

        jLabelLugarCarrera.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelLugarCarrera.setText("Lugar de la carrera");

        jLabelNumeroMaxParticipantes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNumeroMaxParticipantes.setText("Número máx. participantes");

        jTextFieldNombreCarrera.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTextFieldNombreCarrera.setName("Nombre Carrera"); // NOI18N
        jTextFieldNombreCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreCarreraActionPerformed(evt);
            }
        });

        jSpinnerFechaCarrera.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jSpinnerFechaCarrera.setModel(new javax.swing.SpinnerDateModel());

        jComboBoxCiudad.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jComboBoxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S.M.R.A.", "LLANGREU", "MIERES", "POLA LLAVIANA", "CASU" }));
        jComboBoxCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCiudadActionPerformed(evt);
            }
        });

        jComboBoxNumeroMaximoParticipantes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jComboBoxNumeroMaximoParticipantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        jComboBoxNumeroMaximoParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNumeroMaximoParticipantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosCarreraLayout = new javax.swing.GroupLayout(jPanelDatosCarrera);
        jPanelDatosCarrera.setLayout(jPanelDatosCarreraLayout);
        jPanelDatosCarreraLayout.setHorizontalGroup(
            jPanelDatosCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosCarreraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombreCarrera)
                    .addComponent(jLabelNumeroMaxParticipantes)
                    .addComponent(jLabelFechaCarrera)
                    .addComponent(jLabelLugarCarrera))
                .addGap(54, 54, 54)
                .addGroup(jPanelDatosCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxNumeroMaximoParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerFechaCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombreCarrera))
                .addContainerGap())
        );
        jPanelDatosCarreraLayout.setVerticalGroup(
            jPanelDatosCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosCarreraLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelDatosCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosCarreraLayout.createSequentialGroup()
                        .addComponent(jTextFieldNombreCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDatosCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerFechaCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFechaCarrera))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDatosCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLugarCarrera))
                        .addGap(16, 16, 16)
                        .addGroup(jPanelDatosCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxNumeroMaximoParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNumeroMaxParticipantes)))
                    .addComponent(jLabelNombreCarrera))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jButtonSalirCarrera.setBackground(new java.awt.Color(204, 204, 255));
        jButtonSalirCarrera.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonSalirCarrera.setText("Salir");
        jButtonSalirCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirCarreraActionPerformed(evt);
            }
        });

        jButtonValidarCarrera.setBackground(new java.awt.Color(204, 204, 255));
        jButtonValidarCarrera.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonValidarCarrera.setText("Aceptar");
        jButtonValidarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarCarreraActionPerformed(evt);
            }
        });

        jButtonLimpiarCarrera.setBackground(new java.awt.Color(204, 204, 255));
        jButtonLimpiarCarrera.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonLimpiarCarrera.setText("Limpiar");
        jButtonLimpiarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarCarreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonesCarreraLayout = new javax.swing.GroupLayout(jPanelBotonesCarrera);
        jPanelBotonesCarrera.setLayout(jPanelBotonesCarreraLayout);
        jPanelBotonesCarreraLayout.setHorizontalGroup(
            jPanelBotonesCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonesCarreraLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(validationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBotonesCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSalirCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelBotonesCarreraLayout.createSequentialGroup()
                        .addComponent(jButtonLimpiarCarrera)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonValidarCarrera)))
                .addContainerGap())
        );
        jPanelBotonesCarreraLayout.setVerticalGroup(
            jPanelBotonesCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesCarreraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotonesCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBotonesCarreraLayout.createSequentialGroup()
                        .addGroup(jPanelBotonesCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLimpiarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonValidarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSalirCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(validationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTituloCarrera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelDatosCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelBotonesCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelTituloCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanelDatosCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelBotonesCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreCarreraActionPerformed

    private void jButtonSalirCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirCarreraActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirCarreraActionPerformed

    private void jButtonValidarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarCarreraActionPerformed
        Carrera m;
        nombreCarrera = jTextFieldNombreCarrera.getText();
        fechaCarrera = (Date) jSpinnerFechaCarrera.getValue();
        lugarCarrera = (String) jComboBoxCiudad.getSelectedItem();
        String valorComboBox = "";
        valorComboBox = jComboBoxNumeroMaximoParticipantes.getSelectedItem().toString();
        numeroMaxCorredores = Integer.parseInt(valorComboBox);

        //Checkeamos si es un alta o una modificación
        if (carreraModificar == null) {
            m = new Carrera(nombreCarrera, fechaCarrera, lugarCarrera, numeroMaxCorredores);
            LogicaNegocio.getInstance().anadirCarreraLista(m);
            //método para mostrar simplemente un mensaje
            JOptionPane.showMessageDialog(this, "Carrera creada con éxito.",
                    "Validación.", JOptionPane.INFORMATION_MESSAGE);
        } else {
            carreraModificar.setNombreCarrera(nombreCarrera);
            carreraModificar.setFechaCarrera(fechaCarrera);
            carreraModificar.setLugarCarrera(lugarCarrera);
            carreraModificar.setNumeroMaxCorredores(numeroMaxCorredores);
            LogicaNegocio.getInstance().anadirCarreraLista(carreraModificar);
            //método para mostrar simplemente un mensaje
            JOptionPane.showMessageDialog(this, "Carrera modificada con éxito.",
                    "Validación.", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButtonValidarCarreraActionPerformed

    private void jButtonLimpiarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarCarreraActionPerformed
        //devuelve parámetro
        int confirmación = JOptionPane.showConfirmDialog(this, "Quiere limpiar el registro",
                "Confirmación", JOptionPane.YES_NO_CANCEL_OPTION);
        if (confirmación == JOptionPane.YES_OPTION) {
            jTextFieldNombreCarrera.setText("");
            jSpinnerFechaCarrera.setValue("");
            JOptionPane.showMessageDialog(this, "Se ha limpiado la pantalla.",
                    "Limpiar.", JOptionPane.INFORMATION_MESSAGE);
        } else if (confirmación == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "No se ha limpiado la pantalla.",
                    "Limpiar.", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButtonLimpiarCarreraActionPerformed

    private void jComboBoxNumeroMaximoParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNumeroMaximoParticipantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNumeroMaximoParticipantesActionPerformed

    private void jComboBoxCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCiudadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimpiarCarrera;
    private javax.swing.JButton jButtonSalirCarrera;
    private javax.swing.JButton jButtonValidarCarrera;
    private javax.swing.JComboBox<String> jComboBoxCiudad;
    private javax.swing.JComboBox<String> jComboBoxNumeroMaximoParticipantes;
    private javax.swing.JLabel jLabelFechaCarrera;
    private javax.swing.JLabel jLabelLugarCarrera;
    private javax.swing.JLabel jLabelNombreCarrera;
    private javax.swing.JLabel jLabelNumeroMaxParticipantes;
    private javax.swing.JPanel jPanelBotonesCarrera;
    private javax.swing.JPanel jPanelDatosCarrera;
    private javax.swing.JPanel jPanelTituloCarrera;
    private javax.swing.JSpinner jSpinnerFechaCarrera;
    private javax.swing.JTextField jTextFieldNombreCarrera;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel;
    // End of variables declaration//GEN-END:variables
}
