package interfaz;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import interfaz.TablaCarreras;
import interfaz.TablaCorredores;
import java.io.File;
import javax.swing.ImageIcon;
import logica.LogicaNegocio;

/**
 * Los combos se rellenan siempre en constructor porque no funciona, hacer una
 * función para rellenar, privada
 *
 * @author Shaila
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yy");
    private static final String RUTA_LOGO = ".." + File.separator + "imgs" + File.separator + "corredor.png";

    //ojo con crearlo en veinte sitios
    //private LogicaNegocio logicaNegocio;
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() throws ParseException {
        initComponents();

        setLocationRelativeTo(null);
        //Establecer el título de la aplicación
        setTitle("APLICACIÓN GESTIÓN CARRERAS.");
        LogicaNegocio.getInstance().cargarCSVCorredores();
        //Establecer una imagen en una label
        jLabelIcono.setIcon(new ImageIcon(getClass().getResource(RUTA_LOGO)));

        jButtonModificarCarrera.setText("<html><p>ALTA/MODIFICACIÓN</p>"
                + "<p>CARRERAS</p></html>");
        jButtonModificarCorredores.setText("<html><p>ALTA/MODIFICACIÓN</p>"
                + "<p>CORREDORES</p></html>");
        //Establecer el logo del a aplicación
        setIconImage(new ImageIcon(getClass().getResource(RUTA_LOGO)).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPantallaPrincipal = new javax.swing.JPanel();
        jButtonSalirDelTodo = new javax.swing.JButton();
        jButtonModificarCorredores = new javax.swing.JButton();
        jButtonModificarCarrera = new javax.swing.JButton();
        jLabelCarreras = new javax.swing.JLabel();
        jLabelCorredores = new javax.swing.JLabel();
        jLabelIcono = new javax.swing.JLabel();
        jButtonConfiguracion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSalirDelTodo.setBackground(new java.awt.Color(204, 204, 255));
        jButtonSalirDelTodo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonSalirDelTodo.setText("Salir");
        jButtonSalirDelTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirDelTodoActionPerformed(evt);
            }
        });

        jButtonModificarCorredores.setBackground(new java.awt.Color(204, 204, 255));
        jButtonModificarCorredores.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonModificarCorredores.setText("ALTA/MODIFICACIÓN CORREDORES");
        jButtonModificarCorredores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarCorredoresActionPerformed(evt);
            }
        });

        jButtonModificarCarrera.setBackground(new java.awt.Color(204, 204, 255));
        jButtonModificarCarrera.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonModificarCarrera.setText("ALTA/MODIFICACIÓN CARRERAS");
        jButtonModificarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarCarreraActionPerformed(evt);
            }
        });

        jLabelCarreras.setFont(new java.awt.Font("Dialog", 3, 20)); // NOI18N
        jLabelCarreras.setText("CARRERAS");

        jLabelCorredores.setFont(new java.awt.Font("Dialog", 3, 20)); // NOI18N
        jLabelCorredores.setText("CORREDORES");

        jButtonConfiguracion.setBackground(new java.awt.Color(204, 204, 255));
        jButtonConfiguracion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonConfiguracion.setText("Configuración");
        jButtonConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfiguracionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPantallaPrincipalLayout = new javax.swing.GroupLayout(jPanelPantallaPrincipal);
        jPanelPantallaPrincipal.setLayout(jPanelPantallaPrincipalLayout);
        jPanelPantallaPrincipalLayout.setHorizontalGroup(
            jPanelPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPantallaPrincipalLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanelPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPantallaPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jButtonConfiguracion)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalirDelTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPantallaPrincipalLayout.createSequentialGroup()
                        .addGroup(jPanelPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCorredores)
                            .addComponent(jLabelCarreras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonModificarCorredores, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModificarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        jPanelPantallaPrincipalLayout.setVerticalGroup(
            jPanelPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPantallaPrincipalLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCorredores)
                    .addComponent(jButtonModificarCorredores, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPantallaPrincipalLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabelCarreras))
                    .addGroup(jPanelPantallaPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModificarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPantallaPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSalirDelTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(jPanelPantallaPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(53, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelPantallaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelPantallaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**/
    private void jButtonSalirDelTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirDelTodoActionPerformed
        //setVisible(false);        
        this.dispose();
        System.exit(0);//Este usarlo para salir porque el dispose me deja una pantalla.
    }//GEN-LAST:event_jButtonSalirDelTodoActionPerformed

    private void jButtonModificarCorredoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarCorredoresActionPerformed
        TablaCorredores confirmacionValidar
                = new TablaCorredores(new javax.swing.JFrame(), true);
        confirmacionValidar.setVisible(true);
    }//GEN-LAST:event_jButtonModificarCorredoresActionPerformed

    private void jButtonModificarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarCarreraActionPerformed
        TablaCarreras confirmacionValidar
                = new TablaCarreras(new javax.swing.JFrame(), true);
        confirmacionValidar.setVisible(true);
    }//GEN-LAST:event_jButtonModificarCarreraActionPerformed

    private void jButtonConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfiguracionActionPerformed

        DialogConfiguracion dialogoConfiguracion = new DialogConfiguracion(this, true);
        dialogoConfiguracion.setLocationRelativeTo(null);
        dialogoConfiguracion.setVisible(true);


    }//GEN-LAST:event_jButtonConfiguracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PantallaPrincipal().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfiguracion;
    private javax.swing.JButton jButtonModificarCarrera;
    private javax.swing.JButton jButtonModificarCorredores;
    private javax.swing.JButton jButtonSalirDelTodo;
    private javax.swing.JLabel jLabelCarreras;
    private javax.swing.JLabel jLabelCorredores;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JPanel jPanelPantallaPrincipal;
    // End of variables declaration//GEN-END:variables
}
