/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import interfaz.tablas.TableModelParticipantes;
import java.awt.Component;
import java.io.File;
import javax.swing.JFileChooser;
import logica.LogicaNegocio;

/**
 *
 * @author Shaila
 */
public class ResultadoCarreraFinalizada extends javax.swing.JDialog {

    private int posicionCarrera;

    /**
     * Creates new form ResultadoCarrera
     */
    public ResultadoCarreraFinalizada(java.awt.Dialog parent, boolean modal,
            int posicionCarrera) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);

        jLabelNombreCarreraFinalizada.setText(LogicaNegocio.getInstance().
                getListaCarrerasFinalizadas().get(posicionCarrera).getNombreCarrera());
        rellenarTablaCarreras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabelNombreCarreraFinalizada = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResultadoCarrera = new javax.swing.JTable();
        jButtonExportarResultado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNombreCarreraFinalizada.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelNombreCarreraFinalizada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreCarreraFinalizada.setText("Carreras");

        jTableResultadoCarrera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(jTableResultadoCarrera);

        jButtonExportarResultado.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonExportarResultado.setText("Exportar resultado");
        jButtonExportarResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportarResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombreCarreraFinalizada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addComponent(jButtonExportarResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNombreCarreraFinalizada)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExportarResultado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExportarResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportarResultadoActionPerformed
        /*        try {
        System.out.println(gdCarreras.resultadoCarrera(idCarrera));
        gacsv.abrirFicheroEscritura(seleccionarDirectorio(this)
        + File.separator + "ResultadoCarrera"
        + gdCarreras.getListaCarreras().get(idCarrera).getNombre() + ".txt", false);
        gacsv.escribirCadena(gdCarreras.resultadoCarrera(idCarrera));
        gacsv.cerrarFicheroEscritura();
        JOptionPane.showMessageDialog(this, "Resultado exportado");
        } catch (IOException ex) {
        Exceptions.printStackTrace(ex);
        }*/
    }//GEN-LAST:event_jButtonExportarResultadoActionPerformed

    public String seleccionarDirectorio(Component pantalla) {
        File file = null;
        JFileChooser jc = new JFileChooser();
        this.setLocationRelativeTo(null);
        jc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int seleccion = jc.showOpenDialog(pantalla);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            file = jc.getSelectedFile();
        }
        return file.getAbsolutePath();
    }

    private void rellenarTablaCarreras() {
        System.out.println("Prueba "+LogicaNegocio.
                getInstance().getListaCarrerasFinalizadas().get(posicionCarrera).
                getListaParticipantes());
        jTableResultadoCarrera.setModel(new TableModelParticipantes(LogicaNegocio.
                getInstance().getListaCarrerasFinalizadas().get(posicionCarrera).
                getListaParticipantes()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExportarResultado;
    private javax.swing.JLabel jLabelNombreCarreraFinalizada;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResultadoCarrera;
    // End of variables declaration//GEN-END:variables
}
